### ISSUE TITLE
[Bug] - API error: API error Error(AccountNotFound): Account not found by Address(0xa7efb402c71a0ae02489b4938940acb9dc28d544241bf9be181586889faf06c6) and Ledger version(88275062)

### ISSUE THREAD

**Issue by 0xBoji** [movementlabsxyz/aptos-core#64]
# 🐛 Bug

 when publish my package with admin profile and get this error:
 ```
 API error: API error Error(AccountNotFound)
 ```
Move.toml:

admin="0x65ba273bcfa3b38ed20bcf89251b407042a67fe853f6398d7458729b841c2da0"
is correct in manifest

.movement:
 ```
 admin:
   network: Testnet
   private_key: "0x_private_key"
   public_key: "0x65ba273bcfa3b38ed20bcf89251b407042a67fe853f6398d7458729b841c2da0"
   account: a7efb402c71a0ae02489b4938940acb9dc28d544241bf9be181586889faf06c6
   rest_url: "https://aptos.testnet.suzuka.movementlabs.xyz/v1/"
   faucet_url: "https://faucet.testnet.suzuka.movementlabs.xyz/"
  ```
  
but my address found out in explorer with 40 move:
![Screenshot 2024-08-31 065727](https://github.com/user-attachments/assets/0fde187a-8577-433b-aca9-84f943311610)

## Additional context
My CLI:
```
movement move publish --profile admin
